# Generated by Django 6.1.1 on 2026-10-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_comppleted',
            new_name='is_completed',
        ),
    ]
